name: Reusable Dependencies Reviewer

# --------------------------------------------------------------------------
# This workflow only runs when explicitly called by another workflow.
# --------------------------------------------------------------------------
on:
  workflow_call:
    outputs:
      review_conclusion:
        description: "Conclusion from the dependencies review process"
        value: "${{ jobs.dependencies_review.outputs.review_step }}"

env:
  MIN_SCORECARD_LEVEL: '5'

# This workflow is passive so ensure the minimal permissions even if the
# inherited token is more lenient.
permissions:
  contents: read
  issues: none
  pull-requests: none

jobs:
  dependencies_review:
    name: Dependencies Review
    runs-on: ubuntu-latest

    outputs:
      review_step: "${{ steps.set_status.outputs.review_step }}"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          repository: "${{ github.event.repository.full_name }}" # Checkout the caller repo
          fetch-depth: 0 # This may also capture vulnerabilities unrelated to the PR.

      - name: Run Dependency Review
        id: dependency_review
        uses: actions/dependency-review-action@3c4e3dcb1aa7874d2c16be7d79418e9b7efd6261 # v4.8.2
        with:
          show-openssf-scorecard: true
          warn-on-openssf-scorecard-level: "${{ env.MIN_SCORECARD_LEVEL }}"
        continue-on-error: true

      - name: Determine Review Result
        id: set_status
        if: "${{ always() }}"
        env:
          REVIEW_CONCLUSION: "${{ steps.dependency_review.conclusion }}"
        run: |
          if [[ "$REVIEW_CONCLUSION" == "failure" ]]; then
            echo "review_step=failure" >> "$GITHUB_OUTPUT"
          else
            echo "review_step=success" >> "$GITHUB_OUTPUT"
          fi
